name: AIC
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- python==3.7.6
- pytorch==1.6.0
- pillow==6.1 
- torchvision==0.7.0
- fastai==1.0.57
- ipykernel>=4.6.1
- jupyter>=1.0.0
- pytest>=3.6.4
- bqplot
- scikit-learn>=0.19.1
- cython>=0.29.1
- papermill==1.2.0
- black>=18.6b4
- ipywebrtc 
- lxml>=4.3.2
- pre-commit>=1.14.4
- pyyaml>=5.1.2
- requests>=2.22.0
- einops==0.1.0
- cytoolz
- pip:
  - decord==0.3.5
  - nvidia-ml-py3
  - nteract-scrapbook
  - azureml-sdk[notebooks,contrib]>=1.0.30
  - git+https://github.com/youngpark/cocoapi.git#subdirectory=PythonAPI
